// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar/AppBar.vue')['default']
    Card: typeof import('./src/components/Card/Card.vue')['default']
    FormItem: typeof import('./src/components/FormItem/FormItem.vue')['default']
    ImageIconButton: typeof import('./src/components/ImageIconButton/ImageIconButton.vue')['default']
    Popup: typeof import('./src/components/Popup/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox/SearchBox.vue')['default']
    StopIcon: typeof import('./src/components/StopIcon/StopIcon.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VoiceIcon: typeof import('./src/components/VoiceIcon/VoiceIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
